### ISSUE TITLE
Doesn't work on Macbook M2?

### ISSUE THREAD

**Issue by mrwinnie21** [0xMarsyas/Marsyas-DEX-Sniper#1]
I have to use this on and old mac with an intel processor... what gives?

**Comment by CornBrother0x** [comment]
Yeah it's not compatible anymore. As soon as Hashlips or NFTChef or someone else ships a fix I'll update this one. Until then I'm also using an old laptop to run art gens!

**Comment by CornBrother0x** [comment]
closing!
